// Fixed codes only: never persist provider text, arbitrary exception messages,
// command output, keys, or private commit material as diagnostics.
const PLAYER_ERROR_CODES = new Set([
  'MARITIME_REPLY_INVALID_ENVELOPE', 'MARITIME_REPLY_PROVIDER_ERROR',
  'MARITIME_REPLY_NOT_STRING', 'MARITIME_REPLY_EMPTY', 'MARITIME_REPLY_TOO_LARGE',
  'MARITIME_REPLY_SECRET_REJECTED', 'MARITIME_REPLY_INVALID_JSON',
  'MARITIME_REPLY_PROTOCOL_INVALID', 'MARITIME_REPLY_IDENTITY_MISMATCH',
  'PLAYER_SUBMISSION_OUTCOME_UNKNOWN', 'PLAYER_SETTLEMENT_STATE_UNVERIFIED',
  'PLAYER_REVEAL_BUNDLE_MISSING', 'PLAYER_PREPARE_FAILED', 'PLAYER_TOOL_FAILED', 'PLAYER_COMMAND_MISSING',
  'PLAYER_CLI_ARGUMENTS_INVALID', 'PLAYER_INPUT_TOO_LARGE', 'PLAYER_INPUT_INVALID',
  'PLAYER_INPUT_JSON_INVALID', 'PLAYER_SETTINGS_JSON_INVALID', 'PLAYER_STDIN_READ_FAILED',
  'PLAYER_FILESYSTEM_EACCES', 'PLAYER_FILESYSTEM_EPERM',
  'PLAYER_INSUFFICIENT_FUNDS', 'PLAYER_NONCE_EXPIRED', 'PLAYER_REPLACEMENT_UNDERPRICED',
  'PLAYER_SETTINGS_INVALID', 'PLAYER_OPERATIONS_MANIFEST_INVALID', 'PLAYER_SEAT_INVALID',
  'PLAYER_HARNESS_INVALID', 'PLAYER_STORAGE_BOUNDARY_INVALID', 'PLAYER_STORAGE_SYMLINK_REJECTED',
  'PLAYER_STORAGE_MODE_INVALID', 'PLAYER_STORAGE_INVALID', 'PLAYER_LOCK_INVALID', 'PLAYER_SEAT_BUSY',
  'PLAYER_REQUEST_IDENTITY_INVALID', 'PLAYER_CHOICE_LOCATION_INVALID', 'CHOICE_IS_COMMIT_ONLY', 'PLAYER_CHOICE_INVALID',
  'PLAYER_CHOICE_REQUIRED', 'PLAYER_ROLE_COLLISION', 'PLAYER_BUNDLE_INVALID',
  'PLAYER_BUNDLE_IDENTITY_INVALID', 'PLAYER_WALLET_MISMATCH',
  'RUNTIME_DIAGNOSTIC_REQUEST_INVALID', 'RUNTIME_DIAGNOSTIC_CHOICE_INVALID',
  'RUNTIME_DIAGNOSTIC_CHOICE_FORBIDDEN', 'RUNTIME_DIAGNOSTIC_RESPONSE_INVALID',
  'RUNTIME_DIAGNOSTIC_RESPONSE_IDENTITY_MISMATCH', 'PLAYER_DIAGNOSTIC_DEPENDENCY_INVALID',
  'PLAYER_DIAGNOSTIC_VERIFIER_INVALID', 'PLAYER_DIAGNOSTIC_CHAIN_INPUT_INVALID',
  'PLAYER_DIAGNOSTIC_CONTRACT_CHECK_FAILED', 'PLAYER_DIAGNOSTIC_WRAPPER_CHECK_FAILED',
  'PLAYER_DIAGNOSTIC_RECEIPT_INVALID',
  'READINESS_MODEL_ROUTE_UNVERIFIED',
  'PLAYER_CHAIN_VERIFICATION_UNAVAILABLE',
  'REPOSITORY_NOT_CONFIGURED', 'INVALID_REPOSITORY', 'REVISION_CHECK_FAILED',
  'REVISION_MISMATCH', 'DIRTY_REPOSITORY', 'FORBIDDEN_ENV_FILE', 'CHECKOUT_CHANGED',
  'ARTIFACT_DIRECTORY_INVALID', 'ARTIFACT_PATH_INVALID', 'SEAT_MANIFEST_INVALID',
  'SEAT_MANIFEST_DUPLICATE', 'OPERATIONS_MANIFEST_INVALID', 'SIGNER_ROLE_COLLISION',
  'SIGNER_IDENTITY_NOT_CONFIGURED', 'PRIVILEGED_MANIFEST_INVALID',
  'CHAIN_VERIFIER_NOT_CONFIGURED', 'CHAIN_VERIFICATION_FAILED', 'CHAIN_ID_MISMATCH',
  'EXECUTION_ROLE_INVALID', 'EXECUTION_ROLE_VIOLATION', 'CROSS_ROLE_KEY_ENVIRONMENT',
  'INVALID_ARGUMENT', 'SIGNER_INVALID_FORMAT', 'SIGNER_NOT_CONFIGURED',
  'SIGNER_IDENTITY_MISMATCH', 'SIGNER_IDENTITY_VERIFIER_NOT_CONFIGURED',
  'SIGNER_IDENTITY_VERIFICATION_FAILED', 'EXECUTION_ERROR', 'COMMAND_TIMEOUT',
  'OUTPUT_LIMIT_EXCEEDED', 'COMMAND_FAILED', 'INVALID_JSON'
]);

export function safePlayerErrorCode(code, fallback = 'AGENT_REPORTED_ERROR') {
  return typeof code === 'string' && PLAYER_ERROR_CODES.has(code) ? code : fallback;
}

const ETHERS_PLAYER_CODES = new Map([
  ['INSUFFICIENT_FUNDS', 'PLAYER_INSUFFICIENT_FUNDS'],
  ['NONCE_EXPIRED', 'PLAYER_NONCE_EXPIRED'],
  ['REPLACEMENT_UNDERPRICED', 'PLAYER_REPLACEMENT_UNDERPRICED']
]);

export function classifyPlayerBridgeError(result, fallback = 'PLAYER_SUBMISSION_OUTCOME_UNKNOWN') {
  if (result?.error?.code === 'COMMAND_FAILED' && typeof result.stderr === 'string' &&
      Buffer.byteLength(result.stderr, 'utf8') <= 32_768) {
    // Recognize only ethers' fixed code token, never provider prose or arbitrary codes.
    const matches = new Set([...result.stderr.matchAll(
      /(?:^|[\s,(\[])code=(INSUFFICIENT_FUNDS|NONCE_EXPIRED|REPLACEMENT_UNDERPRICED)(?=$|[\s,\])])/g
    )].map(match => match[1]));
    if (matches.size === 1) return ETHERS_PLAYER_CODES.get([...matches][0]);
  }
  return safePlayerErrorCode(result?.error?.code, fallback);
}
